import frappe

def execute():
    frappe.get_doc(
        {
            "is_system_generated":1,
            "dt":"Activity Type",
            "label":"Update to Project Field",
            "fieldname":"custom_update_to_project_field",
            "insert_after":"disabled",
            "length":0,
            "fieldtype":"Data",
            "precision":"",
            "hide_seconds":0,
            "hide_days":0,
            "sort_options":0,
            "fetch_if_empty":0,
            "collapsible":0,
            "depends_on":"",
            "non_negative":0,
            "reqd":0,
            "unique":0,
            "is_virtual":0,
            "read_only":0,
            "ignore_user_permissions":0,
            "hidden":0,
            "print_hide":0,
            "print_hide_if_no_value":0,
            "no_copy":0,
            "allow_on_submit":0,
            "in_list_view":0,
            "in_standard_filter":0,
            "in_global_search":0,
            "in_preview":0,
            "bold":0,
            "report_hide":0,
            "search_index":0,
            "allow_in_quick_entry":0,
            "ignore_xss_filter":0,
            "translatable":1,
            "hide_border":0,
            "show_dashboard":0,
            "description":"",
            "permlevel":0,
            "columns":0,
            "doctype":"Custom Field",
            "module":"Harro"
        }
    ).insert()